version: "2"
run:
  concurrency: 4
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - depguard
    - err113
    - gochecknoglobals
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - noctx
    - wrapcheck
    - noinlineerr
    - wsl # replaced by wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    gocritic:
      disabled-checks:
        - commentFormatting
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
