run:
  concurrency: 4
linters-settings:
  misspell:
    locale: US
  gocritic:
    disabled-checks:
      - commentFormatting
linters:
  enable-all: true
  disable:
    - gomnd # deprecated
    - execinquery # deprecated
    - lll # long lines
    - depguard
    - gochecknoglobals
    - interfacebloat
    - ireturn
    - err113 # remove later!
    - wrapcheck # remove later!
    - noctx # remove later!
